###
POST {{host}}{{api_path}}/user/login
Content-Type: application/json

{
  "username": "test-user",
  "password": "test-password"
}

###
POST {{host}}{{api_path}}/user/create
Content-Type: application/json

{
  "email": "test-user@test-mail.com",
  "username": "test-user",
  "password": "test-password"
}

