name: Server

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/workflows/assemble-android.yml'
      - '.github/workflows/deploy-server.yml'
      - 'android-app/**'
      - 'dev-env/**'
      - 'shared-client/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to push branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build distribution file
        if: job.status == 'success'
        run: |
          chmod +x ./gradlew
          ./gradlew server:shadowJar
        shell: bash

      - name: Upload jar artifact file to workflow run results
        uses: actions/upload-artifact@v2
        with:
          name: MiniGamesServer-1.7.0.jar
          path: server/build/libs/server-1.7.0-all.jar
      - name: Release jar artifact file
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "Server-MiniGames-1.7.0"
          files: server/build/libs/server-1.7.0-all.jar
